apiVersion: v1
data:
  NAMESPACE: "staging"
  MONGO_PASSWORD: Z2xiQDIwMTg=
  DB_URI: mongodb+srv://ednunestec_db_user:5L86B8R9DLJsdWsq@desafiowinnin.jp0bpwj.mongodb.net/?retryWrites=true&w=majority&appName=DesafioWinnin
kind: Secret
metadata:
  name: tvg-simple-backend-secret
  namespace: staging
type: Opaque
